add radio input and group
anthonyshull/mbta_metro pull request #2
Opened 2024-09-06 20:17 UTC by thecristen

Also added them to the demo page.

<img width="583" alt="image" src="https://github.com/user-attachments/assets/b3b99532-2e9c-451a-b7bd-732eca52cafa">

2024-09-06 20:19 UTC, thecristen commented on lib/mbta_metro/components/radio_input.ex
> +defmodule MbtaMetro.Components.Inputs do
d'oh just noticed I forgot to update the name. What're your thoughts on (a) scoping this module to just radio input things vs (b) using this module for any input types and related components?

2024-09-06 21:29 UTC, anthonyshull commented on lib/mbta_metro/components/radio_input.ex
> +defmodule MbtaMetro.Components.Inputs do
Maybe `MbtaMetro.Components.Inputs.Radio`. You can now add it to the component list in the main module https://github.com/anthonyshull/mbta_metro/blob/main/lib/mbta_metro.ex so users can do:

```
use MbtaMetro
```

2024-09-06 21:44 UTC, anthonyshull requested changes

2024-09-06 21:44 UTC, anthonyshull commented on lib/mbta_metro_web/live/demo.html.heex
> +<MbtaMetro.Components.Inputs.radio field={@form[:color]} value="yellow" />
If you include these in mbta_metro.ex you can just use `<.radio ... />`.

2024-09-06 21:44 UTC, anthonyshull commented on lib/mbta_metro_web/live/demo.ex
> +    form = Phoenix.Component.to_form(%{"color" => ["red", "yellow", "blue", "pink"]})
How is this related to the colors in the component? It isn't rendering options or anything. Shouldn't it be a single value? Also, how do we set a default selection?

2024-09-09 14:56 UTC, thecristen commented on lib/mbta_metro_web/live/demo.ex
> +    form = Phoenix.Component.to_form(%{"color" => ["red", "yellow", "blue", "pink"]})
I'll choose a different sample data, since this isn't related to coloring the element :P 
Good point about the default, will add a way to handle this.

2024-09-09 16:50 UTC, thecristen commented
Expanded the scope of this a bit as I realized I wanted to treat radio and checkbox input groups similarly, without duplicating the whole component. So now that's structured as an `<.input_group />`, still using named slots for the list of items in the group. Welcome feedback round 2!

<img width="789" alt="image" src="https://github.com/user-attachments/assets/cc00bfe9-f5b4-4726-a6ef-88c6f7dc6d72">

2024-09-09 17:40 UTC, anthonyshull approved these changes

2024-09-09 17:40 UTC, anthonyshull commented on lib/mbta_metro.ex
> +        Button,
Let's alphabetize these.

2024-09-09 17:40 UTC, anthonyshull commented on lib/mbta_metro/components/inputs.ex
> +    do: "py-2 px-3 w-full inline-flex items-center gap-x-2 has-[:checked]:font-bold"
Probably better to just expand this to a `do` \ `end`.

2024-09-09 18:49 UTC, merged